---
title: "HGDP plotting"
output: html_document
date: "2024-12-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Plotting for HGDP dataset

Load the data and the required libraries:
```{r}
library(clumpplingr)
library(ggplot2)
```

Load `gt_admix` clustering results objects:
```{r}
#fastmixture
hgdp_fastm <- readRDS("../../hgdp_data/clustering/hgdp_fastmixture.rds") #make system file
```

```{r}
#WONT NEED ONCE CARRY OVER META DATA 
#temporarily load meta data
library(readr)
hgdp_meta <- read_tsv("../../fastmixturer/inst/extdata/hgdp/hgdp_zhe_1_12-10-2024/HGDPid_populations.txt")
hgdp_fam <- read.table("../../fastmixturer/inst/extdata/hgdp/hgdp_zhe_1_12-10-2024/hgdp650.qc.hg19.fam",header = FALSE, sep = " ")
pops <- left_join(hgdp_fam, hgdp_meta, by = c("V1" = "Id")) %>%
                          select(V1, population, Region) 
```

Check contents:
```{r}
#fastmixture results
hgdp_fastm %>% summary()
```

```{r}
#admixture results
hgdp_adm_cv %>% summary()
```


## Run clumppling on `fastmixturer` results

```{r}
# run clumppling fastmixture
hgdp_fastm_clump <- hgdp_fastm %>% clumppling()
```

```{r}
# plot all modes
hgdp_fastm_clump %>% autoplot(type = "all_modes")
```

```{r}
# plot all modes with grouping annotation
hgdp_fastm_clump %>% autoplot(type = "all_modes", group = pops$population) #once carry over meta data wont need pops
```

```{r}
#plot major modes
hgdp_fastm_clump %>% autoplot(type = "major_modes", group = pops$population)
```

```{r}
#modes within specified k
hgdp_fastm_clump %>% autoplot(type = "modes_within_k", k = 7, group = pops$population)
```


```{r}
#multipartite all k and all modes
hgdp_fastm_clump %>% autoplot(type = "modes", group = pops$population)
```


## Run clumppling on ADMIXTURE `tidypopgen` results

```{r}
# run clumppling admixture 
hgdp_adm_clump <- hgdp_adm_cv %>% clumppling()
```

```{r}
# plot all modes
hgdp_adm_clump %>% autoplot(type = "all_modes")
```

```{r}
# plot all modes with grouping annotation
hgdp_adm_clump %>% autoplot(type = "all_modes", group = hgdp_adm_cv$group) 
```

```{r}
#plot major modes
hgdp_adm_clump %>% autoplot(type = "major_modes", group = hgdp_adm_cv$group)
```

```{r}
#modes within specified k
hgdp_adm_clump %>% autoplot(type = "modes_within_k", k = 7, group = hgdp_adm_cv$group)
```

```{r}
#multipartite all k and all modes
hgdp_adm_clump %>% autoplot(type = "modes", group = hgdp_adm_cv$group)
```

## Example of plotting with ggplot2

```{r}
q_major_modes <- hgdp_fastm_clump %>% tidy(matrix = "Q_major_modes")
q6_tidied <- q_major_modes[["K6M1"]]

#make rownames a column in pops
pops <- pops %>% rownames_to_column("id") %>%
  mutate(id = as.integer(id)) %>%
  mutate(population = ifelse(population == "French_Basque", "French Basque", population)) %>%  
  mutate(population = ifelse(population == "Biaka_Pygmies", "Biaka Pygmies", population))
#join plot_meta to q6
q6 <- q6_tidied %>% inner_join(pops) 

#get line splits
group_x <- cumsum(table(forcats::fct_inorder(q6$population))) / 6
segment_data = data.frame(
      x = group_x+0.5,
      xend = group_x+0.5,
      y = rep(0,length(group_x)),
      yend = rep(1, length(group_x)))

get_mid_points <- function (vec){
      (vec[-length(vec)] + vec[-1L])/2.
    }
```

```{r}
plt <- q6 %>% ggplot2::ggplot(
  ggplot2::aes(x = id,
               y = percentage,
               fill = q)) +
  # add the columns based on percentage membership to each cluster
  ggplot2::geom_col(width = 1,
                    position = ggplot2::position_stack(reverse = TRUE))+
  # set the y label
  ggplot2::labs(y = "K = 6")+
  # use a theme to match the distruct look, removing most decorations
  theme_distruct() +
  ggplot2::geom_segment(data = segment_data,
                   ggplot2::aes(x = .data$x,
                       y = .data$y,
                       xend = .data$xend,
                       yend = .data$yend),
                       inherit.aes = FALSE,
                   color = "white") +
  # set the colour scale
  ggplot2::scale_fill_viridis_d(guide = "none", direction = -1) +
  ggplot2::scale_x_continuous(breaks = get_mid_points(c(0,group_x)),
                                         labels = names(group_x)) +
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, vjust = 1, 
                                                     hjust=1, face="bold"))

plt 
```







